# questions.py
questions = [
    "How are you feeling today?",
    "Did you experience any stress this week?",
    "Do you feel hopeful about the future?",
    "Have you felt anxious or restless lately?",
    "How is your mood compared to yesterday?",
    "Do you often feel overwhelmed?",
    "Are you having trouble sleeping?",
    "Do you feel motivated to do daily activities?",
    "Do you feel lonely or isolated?",
    "Are you satisfied with your relationships?",
    "How are you feeling today, on a scale of 1-10?",
    "Did something happen today that made you feel anxious or stressed?",
    "What do you think triggered your mood change today?",
    "Do you often feel like your emotions are out of control?",
    "How often do you feel like you have a sense of purpose in your life?",
    "Are you generally satisfied with the way you handle stressful situations?",
    "How do you cope with feelings of anxiety or nervousness?",
    "How do you express your emotions to others?",
    "How do you feel when things don’t go as planned?",
    "Are there particular situations that tend to make you angry?",
    "Do you often feel overwhelmed by your responsibilities?",
    "How do you manage your feelings of sadness or depression?",
    "Have you noticed any patterns in your emotional responses recently?",
    "When was the last time you felt truly happy or content?",
    "Are there people in your life who make you feel more relaxed?",
    "What do you do when you’re feeling really down or unmotivated?",
    "Have you been experiencing any mood swings lately?",
    "What helps you calm down when you’re feeling anxious or stressed?",
    "How do you deal with moments of self-doubt or insecurity?",
    "How often do you feel lonely, even when you’re around others?",
    "Have you ever felt emotionally drained from social interactions?",
    "How do you usually react when you feel misunderstood by others?",
    "Are there certain things that make you feel more confident in yourself?",
    "How do you usually deal with negative thoughts or self-talk?",
    "How often do you worry about the future?",
    "When you feel down, do you seek support from others or prefer to be alone?",
    "What do you think is the root cause of your emotional triggers?",
    "How do you feel when people give you unsolicited advice?",
    "How do you react to unexpected changes in your plans?",
    "How important is it for you to receive validation from others?",
    "Do you find it difficult to forgive others when they hurt you emotionally?",
    "How do you handle situations where you feel misunderstood?",
    "Are you generally open about your feelings or do you keep them hidden?",
    "How do you manage the stress caused by work or school pressures?",
    "When was the last time you felt proud of yourself?",
    "Do you think you are emotionally resilient when faced with challenges?",
    "How do you typically feel after an argument or disagreement?",
    "Do you have a hard time letting go of past emotional wounds?",
    "How often do you feel like you are 'too emotional' for your own good?",
    "How do you define emotional balance or stability?",
    "Do you ever feel like your emotions are being dismissed by others?",
    "How do you usually cope with feelings of hopelessness?",
    "Do you feel like you express gratitude often enough?",
    "How would you describe your emotional intelligence?",
    "How do you respond when others share their emotional struggles with you?",
    "What makes you feel emotionally fulfilled or happy?",
    "Do you feel like you can always control your emotional reactions?",
    "What is your emotional response to stressful situations at work or school?",
    "How do you feel about expressing vulnerability to others?",
    "What would make you feel more at peace with your emotions?",
    "Do you feel comfortable crying in front of others?",
    "How do you usually handle criticism, even if it's constructive?",
    "What is the most difficult emotion for you to express?",
    "Have you ever felt emotionally overwhelmed in a relationship?",
    "How do you feel when someone close to you is upset?",
    "Do you think you are good at setting emotional boundaries?",
    "How do you handle feelings of guilt or shame?",
    "What emotions do you find it hardest to manage?",
    "Do you feel emotionally supported by the people around you?",
    "How do you feel about the way you handle emotional challenges?",
    "Do you have any coping mechanisms that help you deal with tough emotions?",
    "How do you feel about seeking therapy or counseling to work on your emotions?",
    "How often do you feel appreciated by others?",
    "When you’re emotionally exhausted, what helps you recover?",
    "Do you feel like your emotions dictate your decisions?",
    "What emotions do you wish you could express more freely?",
    "Do you ever feel like you're too sensitive for the world around you?",
    "How do you typically react when someone ignores your emotional needs?",
    "Have you ever felt emotionally invalidated by someone close to you?",
    "How do you feel when you're faced with a big, life-changing decision?",
    "Do you think your emotional state affects your physical health?",
    "How do you deal with feelings of envy or resentment?",
    "When was the last time you felt truly content or peaceful?",
    "What makes you feel emotionally strong or empowered?",
    "How do you cope when you feel emotionally detached or numb?",
    "Do you feel like you have enough emotional space in your relationships?",
    "How do you usually feel when you’re under a lot of pressure?",
    "Do you feel like you need more emotional connection in your life?",
    "How do you feel when someone you care about is distant emotionally?",
    "How often do you feel guilty about things you can’t control?",
    "How do you express love and affection toward others?",
    "How do you handle emotional situations in your family?",
    "How often do you feel overwhelmed by the amount of emotional energy you expend?",
    "Do you believe that emotions are a reflection of your personality?",
    "How do you feel when you don't get the emotional support you expect?",
    "How do you react when you receive emotional feedback from someone else?",
    "Do you find it hard to stay emotionally present in conversations?",
    "How do you feel when you need to be the 'strong one' for others?",
    "How do you feel about your emotional intelligence in relationships?",
    "What is the most important emotional lesson you’ve learned so far?",
    "How do you feel when someone refuses to acknowledge your emotions?",
    "What are your emotional triggers in your workplace or school environment?",
    "How do you feel when you have to confront someone about their emotional behavior?",
    "What is the most significant emotional change you’ve experienced in your life?",
    "How do you feel when you experience a setback or failure?",
    "Do you find it easy or difficult to express your emotions through writing?",
    "How do you respond to feelings of emotional numbness or detachment?",
    "How do you express joy in your daily life?",
    "How do you feel when you have to keep your emotions hidden from others?",
    "Do you find it hard to be emotionally vulnerable with loved ones?",
    "How do you manage the emotional pressure of social expectations?",
    "How do you express your fear or anxiety to others?",
    "How do you feel when someone takes your feelings for granted?",
    "How do you handle emotional stress in your relationship?",
    "Do you feel safe emotionally in your current environment?",
    "How do you react to feelings of insecurity in your relationships?",
    "How do you express your anger in healthy ways?",
    "Do you find it hard to acknowledge or validate your own emotions?",
    "How do you feel when you're emotionally drained but need to keep going?",
    "What helps you feel emotionally grounded during chaotic moments?",
    "How do you deal with feelings of jealousy in your relationships?",
    "Do you often find it difficult to forgive yourself emotionally?",
    "How do you feel when someone rejects your emotional offer?",
    "Do you feel more connected to people when they share their emotions with you?",
    "How do you cope when you feel trapped by your emotions?",
    "How do you feel about using art or creativity as a way to express emotions?",
    "How do you respond when someone expresses frustration or anger toward you?",
    "How do you handle moments of emotional vulnerability in public?",
    "How do you feel when you see someone else struggling emotionally?",
    "How do you usually react to feelings of helplessness?",
    "How do you cope when you experience emotional exhaustion?",
    "How do you deal with strong emotional memories from your past?",
    "What is the most supportive emotional response you've ever received?",
    "How do you express relief or release after a stressful event?",
    "Do you find it easier to express emotions through actions than words?",
    "How do you feel when someone doesn’t respect your emotional boundaries?",
    "Do you ever feel like your emotional health is not prioritized enough?",
    "How do you process emotions like guilt, shame, and regret?",
    "How do you feel when you’re stuck in emotional conflict with someone?",
    "How do you handle emotions like sadness or grief during major life changes?"
]
